/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppNavigation: typeof import('./components/organisms/AppNavigation.vue')['default']
    Binder: typeof import('./components/organisms/Binder.vue')['default']
    CardSpace: typeof import('./components/molecules/CardSpace.vue')['default']
    ExpansionDisplay: typeof import('./components/atoms/ExpansionDisplay.vue')['default']
    PlayerListMatch: typeof import('./components/molecules/PlayerListMatch.vue')['default']
    RarirtyDisplay: typeof import('./components/atoms/RarirtyDisplay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveButton: typeof import('./components/atoms/SaveButton.vue')['default']
    UserMenu: typeof import('./components/molecules/UserMenu.vue')['default']
  }
}
